### ISSUE TITLE
Recurrent language model example crashes with `--softmaxtree`

### ISSUE THREAD

**Issue by ninjin** [nicholas-leonard/dp#151]
To replicate, run for example `th recurrentlanguagemodel.lua --softmaxtree`, which goes down in flames with `../rnn/SequencerCriterion.lua:44: SequencerCriterion only decorates stateless criterions`.

**Comment by nicholas-leonard** [comment]
Yeah @jekbradbury brought this up via gitter. I fixed it but somehow didn't merge upstream. `luarocks install rnn` should fix it.

**Comment by ninjin** [comment]
Thank you, now instead it is going down with `rnn/SequencerCriterion.lua:42: attempt to call field 'recursiveAdd' (a nil value)`.  I am assuming that this is due to some Rocks versions being out of sync and have tried to update both rnn and dp, but it still fails.  Is there any way to update all installed Rocks?

**Comment by nicholas-leonard** [comment]
Yeah, nn. `luarocks install nn`.

**Comment by ninjin** [comment]
Wonderful!  Things are now working as intended!
